name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 9 Preview
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.100-preview.3"

      - name: Publish
        run: dotnet publish -c Release -o release

      - name: Copy index.html with updated base href
        run: sed -i 's/<base href="\/" \/>/<base href=".\/" \/>/' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
