name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # ✅ Grants write access to the GITHUB_TOKEN

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # Use a supported version

      - name: Publish Blazor WebAssembly App
        run: |
          dotnet publish PowerOfThree.csproj -c Release -o release --nologo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # ✅ Now has write access
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages
